apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namesepace: default
spec:
  containers:
  - name: nginx
    image: nginx
    command:
      - sleep
      - "3600"
    imagePullPolicy: ifNotPresent
  restartPolicy: Always